using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public sealed class AdoSqliteGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation.Assembly.GetAttributes().Where(x => x.AttributeClass?.Name == "Ado")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                try
                {
                    foreach (var attribute in attributes)
                    {
                        if (attribute.ConstructorArguments.Length != 3)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[1].Value is not string idName)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[2].Value is not bool isAutoIncrementId)
                        {
                            continue;
                        }

                        var properties = type.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Where(p =>
                                !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                            )
                            .ToArray();

                        var id = properties.FirstOrDefault(x => x.Name == idName);

                        if (id is null)
                        {
                            continue;
                        }

                        var stringBuilder = new CSharpStringBuilder(4);
                        stringBuilder.AppendLine("// <auto-generated />");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("#nullable enable");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("using System.Linq;");
                        stringBuilder.AppendLine("using Nestor.Db.Helpers;");
                        stringBuilder.AppendLine("using System.Data;");
                        stringBuilder.AppendLine("using System;");
                        stringBuilder.AppendLine("using System.Threading.Tasks;");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine($"public static class {type.GetTableName()}Ext");
                        stringBuilder.AppendLine("{");
                        AddPropertyNamesField(stringBuilder, properties);
                        stringBuilder.AppendLine();
                        AddGetPropertyValueMethod(stringBuilder, type, properties);
                        stringBuilder.AppendLine();
                        AddGetParametersMethods(stringBuilder, type, properties);
                        stringBuilder.AppendLine();

                        AddCreateInsertQueryMethod(
                            stringBuilder,
                            type,
                            isAutoIncrementId
                                ? properties.Where(x => x.Name != idName).ToArray()
                                : properties
                        );

                        stringBuilder.AppendLine();
                        AddCreateUpdateMethod(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        AddSelectMethod(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        AddReadMethod(stringBuilder, type, properties);
                        stringBuilder.AppendLine();
                        AddReadMethodA(stringBuilder, type, properties);
                        stringBuilder.AppendLine();
                        AddDeleteMethod(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        AddToByteArrayMethod(stringBuilder);
                        stringBuilder.AppendLine();
                        AddCreateUpdateMethod(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine();
                        AddExistsMethod(stringBuilder, type, id);
                        AddGetByIdA(stringBuilder, type, properties, id);
                        stringBuilder.AppendLine("}");

                        spc.AddSource(
                            $"{type}.{nameof(AdoSqliteGenerator)}.g.cs",
                            stringBuilder.ToString()
                        );
                    }
                }
                catch (Exception e)
                {
                    spc.AddSource($"{nameof(AdoSqliteGenerator)}.g.cs", e.ToString());
                }
            }
        );
    }

    private void AddGetParametersMethods(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.QueryParameter}[] GetQueryParameters("
        );

        stringBuilder.AppendLine($"this global::{type} value,");
        stringBuilder.AppendLine("string postfix,");

        stringBuilder.AppendLine(
            $"params global::{TypeFullNames.ReadOnlySpan}<string> propertyNames)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(propertyNames.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return [");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine(
                $"new global::{TypeFullNames.QueryParameter}($\"@{{nameof(value.{property.Name})}}{{postfix}}\", {WriteProperty(property)}),"
            );
        }

        stringBuilder.AppendLine("];");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.QueryParameter}[propertyNames.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < propertyNames.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new global::{TypeFullNames.QueryParameter}($\"@{{propertyNames[i]}}{{postfix}}\", value.GetPropertyValue(propertyNames[i]));"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return parameters;");
        stringBuilder.AppendLine("}");
    }

    private void AddPropertyNamesField(
        CSharpStringBuilder stringBuilder,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static readonly global::{TypeFullNames.ReadOnlyMemory}<string> PropertyNames = new string[] {{\"{string.Join("\", \"", properties.Select(x => x.Name))}\"}};"
        );
    }

    private void AddGetPropertyValueMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine("public static object? GetPropertyValue(");
        stringBuilder.AppendLine($"this global::{type} value,");
        stringBuilder.AppendLine("string propertyName)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("switch(propertyName)");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine(
                $"case nameof(value.{property.Name}): return {WriteProperty(property)};"
            );
        }

        stringBuilder.AppendLine(
            $"default: throw new global::{TypeFullNames.ArgumentOutOfRangeException}("
        );

        stringBuilder.AppendLine("nameof(propertyName),");
        stringBuilder.AppendLine("propertyName,");

        stringBuilder.AppendLine(
            "$\"Specified {propertyName} argument {nameof(propertyName)} was out of the range of valid values.\");"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddCreateInsertQueryMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateInsertQuery("
        );

        stringBuilder.AppendLine($"this global::{type.GetRealFullName()}[] values)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return CreateInsertQuery(values.AsSpan());");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public static {TypeFullNames.SqlQuery} CreateInsertQuery(");

        stringBuilder.AppendLine(
            $"this global::{TypeFullNames.ReadOnlySpan}<global::{type}> values)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(values.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"throw new {TypeFullNames.ArgumentException}(nameof(values));");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.List}<{TypeFullNames.QueryParameter}>(values.Length * {properties.Length});"
        );

        stringBuilder.AppendLine("var valueNames = new string[values.Length];");

        stringBuilder.AppendLine(
            $"var sql = \"INSERT INTO {type.GetTableName()} ({string.Join(", ", properties.Select(x => x.Name))}) VALUES \";"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < values.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "parameters.AddRange(values[i].GetQueryParameters(i.ToString()));"
        );

        stringBuilder.AppendLine(
            $"valueNames[i] = $\"({string.Join(", ", properties.Select(x => $"@{x.Name}{{i}}"))})\";"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("sql += string.Join(\", \", valueNames);");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters.ToArray());");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public static {TypeFullNames.SqlQuery} CreateInsertQuery(");
        stringBuilder.AppendLine($"this global::{type} value)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.List}<{TypeFullNames.QueryParameter}>({properties.Length});"
        );

        stringBuilder.AppendLine(
            $"var sql = \"INSERT INTO {type.GetTableName()} ({string.Join(", ", properties.Select(x => x.Name))}) VALUES ({string.Join(", ", properties.Select(x => $"@{x.Name}"))}); SELECT last_insert_rowid();\";"
        );

        stringBuilder.AppendLine("parameters.AddRange(value.GetQueryParameters(string.Empty));");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters.ToArray());");
        stringBuilder.AppendLine("}");
    }

    private void AddCreateUpdateMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateUpdate{type.GetTableName()}Query("
        );

        stringBuilder.AppendLine($"this global::{id.Type.GetRealFullName()} id,");

        stringBuilder.AppendLine(
            $"params {TypeFullNames.ReadOnlySpan}<global::{TypeFullNames.UpdateProperty}> updates)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.QueryParameter}[updates.Length + 1];"
        );

        stringBuilder.AppendLine(
            $"parameters[0] = new global::{TypeFullNames.QueryParameter}(\"@{id.Name}\", id);"
        );
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < updates.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i + 1] = new global::{TypeFullNames.QueryParameter}($\"@{{updates[i].PropertyName}}\", updates[i].Value);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var sql = $\"UPDATE {type.GetTableName()} SET {{string.Join(\", \", updates.ToArray().Select(x => $\"{{x.PropertyName}} = @{{x.PropertyName}}\"))}} WHERE {id.Name} = @{id.Name}\";"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters);");
        stringBuilder.AppendLine("}");
    }

    private void AddCreateUpdateMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateUpdate{type.GetTableName()}Query("
        );

        stringBuilder.AppendLine($"this global::{type.GetRealFullName()}[] items,");

        stringBuilder.AppendLine(
            $"params global::{TypeFullNames.ReadOnlySpan}<string> propertyNames)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var sql = string.Empty;");

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.List}<global::{TypeFullNames.QueryParameter}>();"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var index = 0; index < items.Length; index++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var item = items[index];");
        stringBuilder.AppendLine(
            "parameters.AddRange(item.GetQueryParameters(index.ToString(), propertyNames));"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if(!propertyNames.IsEmpty)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"sql += $\"UPDATE {type.GetTableName()} SET {{string.Join(\", \", propertyNames.ToArray().Where(x => x != \"{id.Name}\").Select(x => $\"{{x}} = @{{x}}{{index}}\"))}} WHERE {id.Name} = @{id.Name}{{index}};{{{TypeFullNames.Environment}.NewLine}}\";"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("else");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"sql += $\"UPDATE {type.GetTableName()} SET {string.Join(", ", properties.Where(x => x.Name != id.Name).Select(x => $"{x.Name} = @{x.Name}{{index}}"))} WHERE {id.Name} = @{id.Name}{{index}};{{{TypeFullNames.Environment}.NewLine}}\";"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters.ToArray());");
        stringBuilder.AppendLine("}");
    }

    private void AddExistsMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public const string SelectIdsQuery = \"SELECT {id.Name} FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public const string SelectCountQuery = \"SELECT COUNT(*) FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateSelectExists{type.GetTableName()}Query(this global::{id.Type.GetRealFullName()}[] ids)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.QueryParameter}[ids.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < ids.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new global::{TypeFullNames.QueryParameter}($\"@Id{{i}}\", ids[i]);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"return new(SelectIdsQuery + \" WHERE {id.Name} IN (\" + string.Join(\", \", parameters.Select(x => x.Name)) + \")\", parameters);"
        );

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine(
            $"private static async global::{TypeFullNames.ValueTask}<global::{id.Type.GetRealFullName()}[]> ReadExists{type.GetTableName()}Core(this global::{TypeFullNames.DbCommand} command, global::{id.Type.GetRealFullName()}[] ids, global::{TypeFullNames.CancellationToken} ct)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine($"var query = CreateSelectExists{type.GetTableName()}Query(ids);");

        stringBuilder.AppendLine(
            "await using var reader = await command.ExecuteReaderAsync(query, ct);"
        );
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if (!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return [];");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine(
            $"var result = new global::{TypeFullNames.List}<global::{id.Type.GetRealFullName()}>();"
        );
        stringBuilder.AppendLine("while (reader.Read())");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"result.Add({ReadProperty(id)});");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return result.ToArray();");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.ConfiguredValueTaskAwaitable}<global::{id.Type.GetRealFullName()}[]> ReadExists{type.GetTableName()}Async(this global::{TypeFullNames.DbCommand} command, global::{id.Type.GetRealFullName()}[] ids, global::{TypeFullNames.CancellationToken} ct)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return ReadExists{type.GetTableName()}Core(command, ids, ct).ConfigureAwait(false);"
        );

        stringBuilder.AppendLine("}");
    }

    private void AddSelectMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public const string SelectQuery = \"SELECT * FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine($"public const string TableName = \"{type.GetTableName()}\";");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateSelect{type.GetTableName()}Query(this global::{id.Type.GetRealFullName()}[] ids)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.QueryParameter}[ids.Length];"
        );
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < ids.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"parameters[i] = new global::{TypeFullNames.QueryParameter}($\"@Id{{i}}\", ids[i]);"
        );
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"return new(SelectQuery + \" WHERE {id.Name} IN (\" + string.Join(\", \", parameters.Select(x => x.Name)) + \")\", parameters);"
        );

        stringBuilder.AppendLine("}");
    }

    private void AddToByteArrayMethod(CSharpStringBuilder stringBuilder)
    {
        stringBuilder.AppendLine(
            $"private static byte[] ToByteArray(global::{TypeFullNames.Stream} stream)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var buffer = new byte[stream.Length];");
        stringBuilder.AppendLine("var length = stream.Read(buffer);");
        stringBuilder.AppendLine("stream.Close();");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return buffer;");
        stringBuilder.AppendLine("}");
    }

    private void AddReadMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.IEnumerable}<global::{type}> Read{type.GetTableName()}("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield break;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("while (reader.Read())");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield return new()");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine($"{property.Name} = {ReadProperty(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddGetByIdA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.ConfiguredValueTaskAwaitable}<global::{type}?> Get{type.GetTableName()}ByIdAsync("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbCommand} command,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()} id,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}ByIdCore(command, id, ct).ConfigureAwait(false);"
        );
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async global::{TypeFullNames.ValueTask}<global::{type}?> Get{type.GetTableName()}ByIdCore("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbCommand} command,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()} id,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"await using var reader = await command.ExecuteReaderAsync(new global::{TypeFullNames.SqlQuery}(\"SELECT * FROM {type.GetTableName()} WHERE {id.Name} = @id\", new global::{TypeFullNames.QueryParameter}(\"@id\", id)), ct);"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if(!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return null;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("while (await reader.ReadAsync(ct))");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(" return new()");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine($"{property.Name} = {ReadProperty(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return null;");
        stringBuilder.AppendLine("}");
    }

    private void AddReadMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.ConfiguredCancelableAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"return Read{type.GetTableName()}Core(reader, ct).ConfigureAwait(false);"
        );
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async global::{TypeFullNames.IAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Core("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader,");

        stringBuilder.AppendLine(
            $"[global::{TypeFullNames.EnumeratorCancellation}]global::{TypeFullNames.CancellationToken} ct)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield break;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("while (await reader.ReadAsync(ct))");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield return new()");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine($"{property.Name} = {ReadProperty(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.ConfiguredCancelableAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbCommand} command,");
        stringBuilder.AppendLine($"global::{TypeFullNames.SqlQuery} query,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"return Read{type.GetTableName()}Core(command, query, ct).ConfigureAwait(false);"
        );
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async global::{TypeFullNames.IAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Core("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbCommand} command,");
        stringBuilder.AppendLine($"global::{TypeFullNames.SqlQuery} query,");

        stringBuilder.AppendLine(
            $"[global::{TypeFullNames.EnumeratorCancellation}]global::{TypeFullNames.CancellationToken} ct)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "await using var reader = await command.ExecuteReaderAsync(query, ct);"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"await foreach(var row in reader.Read{type.GetTableName()}Async(ct))"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield return row;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddDeleteMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public const string DeleteQuery = \"DELETE FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static {TypeFullNames.SqlQuery} CreateDelete{type.GetTableName()}Query("
        );

        stringBuilder.AppendLine($"this global::{id.Type.GetRealFullName()}[] ids)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.QueryParameter}[ids.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < ids.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new global::{TypeFullNames.QueryParameter}($\"@Id{{i}}\", ids[i]);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"return new(DeleteQuery + \" WHERE {id.Name} IN (\" + string.Join(\", \", parameters.Select(x => x.Name)) + \")\", parameters);"
        );

        stringBuilder.AppendLine("}");
    }

    private string ReadProperty(IPropertySymbol property)
    {
        if (
            property.Type is INamedTypeSymbol
            {
                TypeKind: TypeKind.Enum,
                EnumUnderlyingType: not null,
            } named
        )
        {
            return $"(global::{property.Type}){ReadProperty(named.EnumUnderlyingType.ToString(), property.Name)}";
        }

        return ReadProperty(property.Type.ToString(), property.Name);
    }

    private string WriteProperty(IPropertySymbol property)
    {
        if (
            property.Type is INamedTypeSymbol
            {
                TypeKind: TypeKind.Enum,
                EnumUnderlyingType: not null,
            } named
        )
        {
            return $"(global::{property.Type}){WriteProperty(named.EnumUnderlyingType.ToString(), property.Name)}";
        }

        return WriteProperty(property.Type.ToString(), property.Name);
    }

    private string ReadProperty(string propertyType, string propertyName)
    {
        return propertyType switch
        {
            "bool" => $"reader.GetBoolean(\"{propertyName}\")",
            "int" => $"reader.GetInt32(\"{propertyName}\")",
            "string" => $"reader.GetString(\"{propertyName}\")",
            "long" => $"reader.GetInt64(\"{propertyName}\")",
            "byte" => $"reader.GetByte(\"{propertyName}\")",
            "ushort" => $"(ushort)reader.GetInt32(\"{propertyName}\")",
            "uint" => $"(uint)reader.GetInt64(\"{propertyName}\")",
            "ulong" =>
                $"global::{TypeFullNames.BitConverter}.ToUInt64(global::{TypeFullNames.BitConverter}.GetBytes(reader.GetInt64(\"{propertyName}\")))",
            "sbyte" => $"(sbyte)reader.GetInt16(\"{propertyName}\")",
            "short" => $"reader.GetInt16(\"{propertyName}\")",
            "float" => $"reader.GetFloat(\"{propertyName}\")",
            "double" => $"reader.GetDouble(\"{propertyName}\")",
            "decimal" => $"reader.GetDecimal(\"{propertyName}\")",
            "char" => $"reader.GetChar(\"{propertyName}\")",
            "byte[]" => $"ToByteArray(reader.GetStream(\"{propertyName}\"))",
            TypeFullNames.TimeOnly =>
                $"new global::{TypeFullNames.TimeOnly}(reader.GetInt64(\"{propertyName}\"))",
            TypeFullNames.TimeSpan =>
                $"new global::{TypeFullNames.TimeSpan}(reader.GetInt64(\"{propertyName}\"))",
            TypeFullNames.DateOnly =>
                $"global::{TypeFullNames.DateOnly}.FromDayNumber(reader.GetInt32(\"{propertyName}\"))",
            TypeFullNames.DateTime =>
                $"new global::{TypeFullNames.DateTime}(reader.GetInt64(\"{propertyName}\"))",
            TypeFullNames.DateTimeOffset =>
                $"new global::{TypeFullNames.DateTimeOffset}(reader.GetInt64(\"{propertyName}\"), global::{TypeFullNames.TimeSpan}.Zero)",
            TypeFullNames.Guid =>
                $"global::{TypeFullNames.Guid}.Parse(reader.GetString(\"{propertyName}\"))",
            _ => propertyType.EndsWith("?")
                ? $"reader.IsDBNull(\"{propertyName}\") ? null : {ReadProperty(propertyType.Substring(0, propertyType.Length - 1), propertyName)}"
                : propertyType,
        };
    }

    private string WriteProperty(string propertyType, string propertyName, bool isNullable = false)
    {
        var nullableSuffix = isNullable ? "?" : "";

        return propertyType switch
        {
            "bool" => $"value.{propertyName}",
            "int" => $"value.{propertyName}",
            "string" => $"value.{propertyName}",
            "long" => $"value.{propertyName}",
            "byte" => $"value.{propertyName}",
            "ushort" => $"value.{propertyName}",
            "uint" => $"value.{propertyName}",
            "ulong" => isNullable
                ? $"value.{propertyName}.HasValue ? global::{TypeFullNames.BitConverter}.ToInt64(global::{TypeFullNames.BitConverter}.GetBytes(value.{propertyName}.Value)) : null"
                : $"global::{TypeFullNames.BitConverter}.ToInt64(global::{TypeFullNames.BitConverter}.GetBytes(value.{propertyName}))",
            "sbyte" => $"value.{propertyName}",
            "short" => $"value.{propertyName}",
            "float" => $"value.{propertyName}",
            "double" => $"value.{propertyName}",
            "decimal" => $"value.{propertyName}",
            "char" => $"value.{propertyName}",
            "byte[]" => $"value.{propertyName}",
            TypeFullNames.TimeOnly => $"value.{propertyName}{nullableSuffix}.Ticks",
            TypeFullNames.TimeSpan => $"value.{propertyName}{nullableSuffix}.Ticks",
            TypeFullNames.DateOnly => $"value.{propertyName}{nullableSuffix}.DayNumber",
            TypeFullNames.DateTime => $"value.{propertyName}{nullableSuffix}.Ticks",
            TypeFullNames.DateTimeOffset => $"value.{propertyName}{nullableSuffix}.UtcTicks",
            TypeFullNames.Guid => $"value.{propertyName}",
            _ => propertyType.EndsWith("?")
                ? WriteProperty(
                    propertyType.Substring(0, propertyType.Length - 1),
                    propertyName,
                    true
                )
                : propertyType,
        };
    }
}
