using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public sealed class EditModelGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation
                    .Assembly.GetAttributes()
                    .Where(x => x.AttributeClass?.Name == "EditModel")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                try
                {
                    foreach (var attribute in attributes)
                    {
                        if (attribute.ConstructorArguments.Length != 2)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[1].Value is not string idName)
                        {
                            continue;
                        }

                        var stringBuilder = new CSharpStringBuilder(4);

                        var properties = type.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Where(p =>
                                !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                            )
                            .ToArray();

                        var id = properties.FirstOrDefault(x => x.Name == idName);

                        if (id is null)
                        {
                            continue;
                        }

                        stringBuilder.AppendLine("// <auto-generated />");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("#nullable enable");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("using System.Linq;");
                        stringBuilder.AppendLine("using Nestor.Db.Models;");
                        stringBuilder.AppendLine("using Gaia.Helpers;");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                        stringBuilder.AppendLine();
                        CreateEditClass(stringBuilder, type, properties, id);
                        var text = stringBuilder.ToString();
                        spc.AddSource($"EventEntity.{type}.g.cs", text);
                    }
                }
                catch (Exception e)
                {
                    spc.AddSource("EventEntity.g.cs", e.ToString());
                }
            }
        );
    }

    private void CreateEditClass(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine($"public sealed partial class Edit{type.Name}");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"public Edit{type.Name}(global::{id.Type.GetRealFullName()} id)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"{id.Name} = id;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public Edit{type.Name}(global::{type.GetRealFullName()} value)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"{id.Name} = value.{id.Name};");

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"IsEdit{property.Name} = true;");
            stringBuilder.AppendLine($"{property.Name} = value.{property.Name};");
        }

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public global::{id.Type.GetRealFullName()} {id.Name} {{ get; }}"
        );

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"public bool IsEdit{property.Name} {{ get; set; }}");
            var realFullName = property.Type.GetRealFullName();

            if (realFullName == TypeFullNames.String)
            {
                stringBuilder.AppendLine(
                    $"public string {property.Name} {{ get; set; }} = string.Empty;"
                );
            }
            else if (realFullName.EndsWith("[]"))
            {
                stringBuilder.AppendLine(
                    $"public {realFullName} {property.Name} {{ get; set; }} = [];"
                );
            }
            else
            {
                stringBuilder.AppendLine($"public {realFullName} {property.Name} {{ get; set; }}");
            }
        }

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("public int GetEdited()");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var count = 0;");
        stringBuilder.AppendLine();

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(IsEdit{property.Name})");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("count++;");
            stringBuilder.AppendLine("}");
        }
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return count;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }
}
