using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Nestor.SourceGenerator;

[Generator]
public class InsertQueryGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Filter classes with [SourceEntity] attribute
        var provider = context
            .SyntaxProvider.CreateSyntaxProvider(
                predicate: (s, _) => s is ClassDeclarationSyntax { AttributeLists.Count: > 0 },
                transform: (ctx, _) => GetSemanticTargetForGeneration(ctx)
            )
            .Where(t => t is not null)!;

        context.RegisterSourceOutput(provider.Collect(), Execute);
    }

    private static TypeToGenerate? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var symbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

        if (symbol is null)
        {
            return null;
        }

        var attribute = symbol
            .GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "InsertQuery");

        if (attribute is null)
        {
            return null;
        }

        var properties = symbol.GetMembers().OfType<IPropertySymbol>().Select(p => p.Name).ToList();

        return new(symbol.ContainingNamespace.ToDisplayString(), symbol.Name, properties);
    }

    private static void Execute(
        SourceProductionContext context,
        ImmutableArray<TypeToGenerate> types
    )
    {
        foreach (var type in types)
        {
            var sb = new StringBuilder();
            var columns = string.Join(", ", type.Properties);
            var parameters = string.Join(", ", type.Properties.Select(p => "@" + p));

            sb.Append(
                $$"""
// <auto-generated/>
namespace {{type.Namespace}};

public partial class {{type.Name}}
{
    public const string InsertSqlite = "INSERT INTO {{type.TableName}} ({{columns}}) VALUES ({{parameters}});";
}
"""
            );
            context.AddSource(
                $"{type.Name}.InsertQuery.g.cs",
                SourceText.From(sb.ToString(), Encoding.UTF8)
            );
        }
    }

    private record TypeToGenerate
    {
        public TypeToGenerate(string ns, string name, List<string> properties)
        {
            Namespace = ns;
            Name = name;
            Properties = properties;
            var entityName = name.Substring(0, name.Length - 6);
            TableName = entityName + "s";
        }

        public string Namespace { get; }
        public string Name { get; }
        public string TableName { get; }
        public List<string> Properties { get; }
    }
}
