using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public sealed class LiteDbSourceEntityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation
                    .Assembly.GetAttributes()
                    .Where(x => x.AttributeClass?.Name == "LiteDbSourceEntity")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                try
                {
                    foreach (var attribute in attributes)
                    {
                        if (attribute.ConstructorArguments.Length != 2)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[1].Value is not string idName)
                        {
                            continue;
                        }

                        var stringBuilder = new CSharpStringBuilder(4);

                        var properties = type.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Where(p =>
                                !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                            )
                            .ToArray();

                        var id = properties.FirstOrDefault(x => x.Name == idName);

                        if (id is null)
                        {
                            continue;
                        }

                        stringBuilder.AppendLine("// <auto-generated />");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("#nullable enable");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("using System;");
                        stringBuilder.AppendLine("using Nestor.Db.Models;");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                        stringBuilder.AppendLine();

                        stringBuilder.AppendLine(
                            $"public static class {type.Name}LiteDbSourceExtensions"
                        );

                        stringBuilder.AppendLine("{");
                        CreateAddEntities(stringBuilder, type, properties, id);
                        stringBuilder.AppendLine();
                        CreateDeleteEntities(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        CreateEditMethod(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine("}");
                        var text = stringBuilder.ToString();
                        spc.AddSource($"{type}.LiteDbSource.g.cs", text);
                    }
                }
                catch (Exception e)
                {
                    spc.AddSource("LiteDbSource.g.cs", e.ToString());
                }
            }
        );
    }

    private void CreateEditMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine("public static void EditEntities(");
        stringBuilder.AppendLine($"this global::{TypeFullNames.IDatabase} database,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine($"global::{TypeFullNames.Guid} transactionId,");
        stringBuilder.AppendLine("bool isUseEvents,");
        stringBuilder.AppendLine($"params global::{type.GetNamespace()}.Edit{type.Name}[] edits)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(edits.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"var valueCollection = database.Get{type.Name}Collection();");
        stringBuilder.AppendLine("valueCollection.Edit(edits);");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if(isUseEvents)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"var eventCollection = database.GetEventEntityCollection();");
        stringBuilder.AppendLine($"var ids = edits.Select(x => x.{id.Name}).Distinct().ToArray();");
        stringBuilder.AppendLine("var index = 0;");
        stringBuilder.AppendLine("var eventCount = edits.Sum(x => x.GetEdited());");
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");

        stringBuilder.AppendLine(
            $"var events = new global::{TypeFullNames.BsonDocument}[eventCount];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < edits.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var edit = edits[i];");
        stringBuilder.AppendLine();

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(edit.IsEdit{property.Name})");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = edit.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");

            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{property.GetEntityValueName()} = {property.GetEntityTypeFullName()}edit.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("CreatedAt = now,");
            stringBuilder.AppendLine("}.ToBsonDocument();");
            stringBuilder.AppendLine("}");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine("eventCollection.Insert(events);");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void CreateDeleteEntities(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static void DeleteEntities(this {TypeFullNames.IDatabase} database, string userId, global::{TypeFullNames.Guid} transactionId, bool isUseEvents, params global::{id.Type.GetRealFullName()}[] ids)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(ids.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"var valueCollection = database.Get{type.Name}Collection();");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if(isUseEvents)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var eventCollection = database.GetEventEntityCollection();");
        stringBuilder.AppendLine("eventCollection.Insert(ids.Select(x =>");
        stringBuilder.AppendLine($"new global::{TypeFullNames.EventEntity}");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("UserId = userId,");
        stringBuilder.AppendLine("EntityId = x,");
        stringBuilder.AppendLine("TransactionId = transactionId,");
        stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
        stringBuilder.AppendLine("EntityProperty = \"__IS_DELETED__\",");
        stringBuilder.AppendLine("EntityBooleanValue = true,");
        stringBuilder.AppendLine("CreatedAt = now,");
        stringBuilder.AppendLine("}.ToBsonDocument()).ToArray());");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"valueCollection.Delete(global::{TypeFullNames.Query}.In(\"_id\", ids.Select(x => new global::{TypeFullNames.BsonValue}(x))));"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateAddEntities(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static void AddEntities(this {TypeFullNames.IDatabase} database, string userId, global::{TypeFullNames.Guid} transactionId, bool isUseEvents, global::{type.GetRealFullName()}[] items)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(items.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"var valueCollection = database.Get{type.Name}Collection();");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("if(isUseEvents)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var eventCollection = database.GetEventEntityCollection();");
        stringBuilder.AppendLine("var index = 0;");

        stringBuilder.AppendLine(
            $"var events = new {TypeFullNames.EventEntity}[items.Length * {properties.Length - 1}];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("foreach (var item in items)");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = item.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{property.GetEntityValueName()} = {property.GetEntityTypeFullName()}item.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("};");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("eventCollection.Insert(events.Select(x => x.ToBsonDocument()));");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("valueCollection.Insert(items.Select(x => x.ToBsonDocument()));");
        stringBuilder.AppendLine("}");
    }
}
