using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public sealed class LiteDbGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation.Assembly.GetAttributes().Where(x => x.AttributeClass?.Name == "LiteDb")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                foreach (var attribute in attributes)
                {
                    if (attribute.ConstructorArguments.Length != 3)
                    {
                        continue;
                    }

                    if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                    {
                        continue;
                    }

                    if (attribute.ConstructorArguments[1].Value is not string idName)
                    {
                        continue;
                    }

                    if (attribute.ConstructorArguments[2].Value is not bool isAutoIncrementId)
                    {
                        continue;
                    }

                    var properties = type.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p =>
                            !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                        )
                        .ToArray();

                    var id = properties.FirstOrDefault(x => x.Name == idName);

                    if (id is null)
                    {
                        continue;
                    }

                    var stringBuilder = new CSharpStringBuilder(4);
                    stringBuilder.AppendLine("// <auto-generated />");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("#nullable enable");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("using System;");
                    stringBuilder.AppendLine("using Nestor.Db.LiteDb.Helpers;");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine($"public static class {type.Name}LiteDbExtension");
                    stringBuilder.AppendLine("{");
                    CreateToBsonDocument(stringBuilder, type, properties, id, isAutoIncrementId);
                    stringBuilder.AppendLine();
                    CreateToValue(stringBuilder, type, properties, id);
                    stringBuilder.AppendLine();
                    CreateGetCollection(stringBuilder, type, id);
                    stringBuilder.AppendLine();
                    CreateDropCollection(stringBuilder, type);
                    stringBuilder.AppendLine();
                    CreateEditValues(stringBuilder, type, properties, id);
                    stringBuilder.AppendLine("}");

                    spc.AddSource($"LiteDb.{type}.g.cs", stringBuilder.ToString());
                }
            }
        );
    }

    private void CreateEditValues(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static void Edit(this global::{TypeFullNames.UltraLiteCollection}<global::{TypeFullNames.BsonDocument}> collection, params global::{TypeFullNames.Span}<Edit{type.Name}> edits)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(edits.IsEmpty)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("foreach(var edit in edits)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var document = collection.FindById(new global::{TypeFullNames.BsonValue}(edit.{id.Name}));"
        );

        foreach (var property in properties)
        {
            if (property.Name == id.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(edit.IsEdit{property.Name})");
            stringBuilder.AppendLine("{");

            stringBuilder.AppendLine(
                $"document[\"{property.Name}\"] = edit.{property.Name}{GetToBsonValue(property)};"
            );

            stringBuilder.AppendLine("}");
        }

        stringBuilder.AppendLine("collection.Update(document);");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void CreateDropCollection(CSharpStringBuilder stringBuilder, INamedTypeSymbol type)
    {
        stringBuilder.AppendLine(
            $"public static bool Drop{type.Name}Collection(this global::{TypeFullNames.UltraLiteDatabase} database)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"return database.DropCollection(\"{type.Name}\");");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static bool Drop{type.Name}Collection(this global::{TypeFullNames.IDatabase} database)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"return database.DropCollection(\"{type.Name}\");");
        stringBuilder.AppendLine("}");
    }

    private void CreateGetCollection(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        var bsonAutoId = id.Type.Name switch
        {
            "Int32" or "Int64" or "Guid" => id.Type.Name,
            _ => "ObjectId",
        };

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.UltraLiteCollection}<global::{TypeFullNames.BsonDocument}> Get{type.Name}Collection(this global::{TypeFullNames.UltraLiteDatabase} database)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"var collection = database.GetCollection(\"{type.Name}\", global::{TypeFullNames.BsonAutoId}.{bsonAutoId});"
        );
        stringBuilder.AppendLine("return collection;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.UltraLiteCollection}<global::{TypeFullNames.BsonDocument}> Get{type.Name}Collection(this global::{TypeFullNames.IDatabase} database)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"var collection = database.GetCollection(\"{type.Name}\", global::{TypeFullNames.BsonAutoId}.{bsonAutoId});"
        );
        stringBuilder.AppendLine("return collection;");
        stringBuilder.AppendLine("}");
    }

    private void CreateToBsonDocument(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id,
        bool isAutoIncrementId
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.BsonDocument} ToBsonDocument(this global::{type} value)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"var document = new global::{TypeFullNames.BsonDocument}();");

        foreach (var property in properties)
        {
            if (property.Name == id.Name)
            {
                if (!isAutoIncrementId)
                {
                    stringBuilder.AppendLine($"document[\"_id\"] = value.{property.Name};");
                }

                continue;
            }

            stringBuilder.AppendLine(
                $"document[\"{property.Name}\"] = value.{property.Name}{GetToBsonValue(property)};"
            );
        }

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return document;");
        stringBuilder.AppendLine("}");
    }

    private string GetToBsonValue(IPropertySymbol property)
    {
        return GetToBsonValue(property.Type);
    }

    private string GetToValue(IPropertySymbol property)
    {
        var value = GetToValue(property.Type);

        if (string.IsNullOrWhiteSpace(value))
        {
            if (property.Type.NullableAnnotation == NullableAnnotation.Annotated)
            {
                if (property.Type.IsValueType)
                {
                    return $"document.Get{((INamedTypeSymbol)property.Type).TypeArguments[0].GetRealName()}(\"{property.Name}\")";
                }
                else
                {
                    return $"document.Get{property.Type.GetRealName()}(\"{property.Name}\")";
                }
            }
        }

        return $"document[\"{property.Name}\"]{value}";
    }

    private string GetToValue(ITypeSymbol symbol)
    {
        var name = GetToValueName(symbol);

        if (string.IsNullOrWhiteSpace(name))
        {
            return string.Empty;
        }

        return $".To{name}()";
    }

    private string GetToValueName(ITypeSymbol symbol)
    {
        if (symbol is IArrayTypeSymbol array)
        {
            return array.NullableAnnotation == NullableAnnotation.Annotated
                ? $"{GetToValueName(array.ElementType)}ArrayOrNull"
                : $"{GetToValueName(array.ElementType)}Array";
        }

        if (symbol is INamedTypeSymbol { EnumUnderlyingType: not null })
        {
            return symbol.NullableAnnotation == NullableAnnotation.Annotated
                ? $"EnumOrNull<global::{symbol.GetRealFullName()}>"
                : $"Enum<global::{symbol.GetRealFullName()}>";
        }

        return symbol.Name switch
        {
            "Byte"
            or "DateTimeOffset"
            or "UInt16"
            or "Int16"
            or "UInt32"
            or "UInt64"
            or "Char"
            or "SByte"
            or "DateOnly"
            or "TimeOnly"
            or "TimeSpan" => symbol.NullableAnnotation == NullableAnnotation.Annotated
                ? $"{symbol.Name}OrNull"
                : symbol.Name,
            "Nullable" => GetToValueName(((INamedTypeSymbol)symbol).TypeArguments[0]),
            _ => string.Empty,
        };
    }

    private string GetToBsonValue(ITypeSymbol symbol)
    {
        if (symbol is INamedTypeSymbol { EnumUnderlyingType: not null })
        {
            return $".ToBsonValue<global::{symbol.GetRealFullName()}>()";
        }

        return symbol.Name switch
        {
            "Byte"
            or "DateTimeOffset"
            or "UInt16"
            or "UInt32"
            or "UInt64"
            or "Char"
            or "DateOnly"
            or "TimeOnly"
            or "TimeSpan" => ".ToBsonValue()",
            "Nullable" => GetToBsonValue(((INamedTypeSymbol)symbol).TypeArguments[0]),
            _ => string.Empty,
        };
    }

    private void CreateToValue(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{type} To{type.Name}(this global::{TypeFullNames.BsonDocument} document)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"return new global::{type}");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            if (property.Name == id.Name)
            {
                stringBuilder.AppendLine($"{property.Name} = document[\"_id\"],");

                continue;
            }

            stringBuilder.AppendLine($"{property.Name} = {GetToValue(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
    }
}
