using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public class SourceEntityGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation
                    .Assembly.GetAttributes()
                    .Where(x => x.AttributeClass?.Name == "SourceEntity")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                try
                {
                    foreach (var attribute in attributes)
                    {
                        if (attribute.ConstructorArguments.Length != 2)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                        {
                            continue;
                        }

                        if (attribute.ConstructorArguments[1].Value is not string idName)
                        {
                            continue;
                        }

                        var stringBuilder = new CSharpStringBuilder(4);

                        var properties = type.GetMembers()
                            .OfType<IPropertySymbol>()
                            .Where(p =>
                                !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                            )
                            .ToArray();

                        var id = properties.FirstOrDefault(x => x.Name == idName);

                        if (id is null)
                        {
                            continue;
                        }

                        stringBuilder.AppendLine("// <auto-generated />");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("#nullable enable");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine("using System.Linq;");
                        stringBuilder.AppendLine("using Nestor.Db.Models;");
                        stringBuilder.AppendLine("using Gaia.Helpers;");
                        stringBuilder.AppendLine();
                        stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                        stringBuilder.AppendLine();

                        stringBuilder.AppendLine(
                            $"public static class {type.GetTableName()}SourceExt"
                        );

                        stringBuilder.AppendLine("{");
                        CreateAddMethod(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine();
                        CreateAddMethodA(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine();
                        CreateDeleteMethod(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        CreateDeleteMethodA(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        CreateEditMethod(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine();
                        CreateEditMethodA(stringBuilder, type, id, properties);
                        stringBuilder.AppendLine();
                        CreateGetMethod(stringBuilder, type, id);
                        stringBuilder.AppendLine();
                        CreateGetMethodA(stringBuilder, type, id);
                        stringBuilder.AppendLine("}");
                        stringBuilder.AppendLine();
                        CreateEditClass(stringBuilder, type, properties, id);
                        var text = stringBuilder.ToString();
                        spc.AddSource($"EventEntity.{type}.g.cs", text);
                    }
                }
                catch (Exception e)
                {
                    spc.AddSource("EventEntity.g.cs", e.ToString());
                }
            }
        );
    }

    private void CreateGetMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{type.GetRealFullName()}[] Get{type.GetTableName()}("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{TypeFullNames.SqlQuery} query)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("using var reader = session.ExecuteReader(query);");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"return reader.Read{type.GetTableName()}().ToArray();");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{type.GetRealFullName()}[] Get{type.GetTableName()}("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}(session, {type.GetTableName()}Ext.SelectQuery);"
        );

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{type.GetRealFullName()}[] Get{type.GetTableName()}("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()}[] ids)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}(session, ids.CreateSelect{type.GetTableName()}Query());"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateGetMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable}<global::{type.GetRealFullName()}[]> Get{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{TypeFullNames.SqlQuery} query,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}Core(session, query, ct).ConfigureAwait(false);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async {TypeFullNames.ValueTask}<global::{type.GetRealFullName()}[]> Get{type.GetTableName()}Core("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{TypeFullNames.SqlQuery} query,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "await using var reader = await session.ExecuteReaderAsync(query, ct);"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"return (await reader.Read{type.GetTableName()}Async(ct).ToEnumerableAsync()).ToArray();"
        );

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable}<global::{type.GetRealFullName()}[]> Get{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}Async(session, {type.GetTableName()}Ext.SelectQuery, ct);"
        );

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable}<global::{type.GetRealFullName()}[]> Get{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()}[] ids,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"return Get{type.GetTableName()}Async(session, ids.CreateSelect{type.GetTableName()}Query(), ct);"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateDeleteMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine("public static void DeleteEntities(");
        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"params global::{id.Type.GetRealFullName()}[] ids)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(ids.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("session.ExecuteNonQuery(ids.Select(x =>");
        stringBuilder.AppendLine($"new global::{TypeFullNames.EventEntity}");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("UserId = userId,");
        stringBuilder.AppendLine("EntityId = x,");
        stringBuilder.AppendLine("TransactionId = transactionId,");
        stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
        stringBuilder.AppendLine("EntityProperty = \"__IS_DELETED__\",");
        stringBuilder.AppendLine("EntityBooleanValue = true,");
        stringBuilder.AppendLine("CreatedAt = now,");
        stringBuilder.AppendLine("}).ToArray().CreateInsertQuery());");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"session.ExecuteNonQuery(ids.CreateDelete{type.GetTableName()}Query());"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateDeleteMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable} DeleteEntitiesAsync("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()}[] ids,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "return DeleteEntitiesCore(session, userId, transactionId, ids, ct).ConfigureAwait(false);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async {TypeFullNames.ValueTask} DeleteEntitiesCore("
        );

        stringBuilder.AppendLine($"global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{id.Type.GetRealFullName()}[] ids,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(ids.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("await session.ExecuteNonQueryAsync(ids.Select(x =>");
        stringBuilder.AppendLine($"new global::{TypeFullNames.EventEntity}");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("UserId = userId,");
        stringBuilder.AppendLine("EntityId = x,");
        stringBuilder.AppendLine("TransactionId = transactionId,");
        stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
        stringBuilder.AppendLine("EntityProperty = \"__IS_DELETED__\",");
        stringBuilder.AppendLine("EntityBooleanValue = true,");
        stringBuilder.AppendLine("CreatedAt = now,");
        stringBuilder.AppendLine("}).ToArray().CreateInsertQuery(), ct);");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"await session.ExecuteNonQueryAsync(ids.CreateDelete{type.GetTableName()}Query(), ct);"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateEditMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine("public static void EditEntities(");
        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"params global::{type.GetNamespace()}.Edit{type.Name}[] edits)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(edits.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"var ids = edits.Select(x => x.{id.Name}).Distinct().ToArray();");
        stringBuilder.AppendLine("var index = 0;");
        stringBuilder.AppendLine("var eventCount = edits.Sum(x => x.GetEdited());");
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");
        stringBuilder.AppendLine($"var queries = new {TypeFullNames.SqlQuery}[edits.Length];");

        stringBuilder.AppendLine(
            $"var events = new global::{TypeFullNames.EventEntity}[eventCount];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < edits.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var edit = edits[i];");
        stringBuilder.AppendLine("var updateIndex = 0;");

        stringBuilder.AppendLine(
            $"var updates = new {TypeFullNames.UpdateProperty}[edit.GetEdited()];"
        );

        stringBuilder.AppendLine();

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(edit.IsEdit{property.Name})");
            stringBuilder.AppendLine("{");

            stringBuilder.AppendLine(
                $"updates[updateIndex++] = new global::{TypeFullNames.UpdateProperty}(nameof(edit.{property.Name}), edit.{property.Name});"
            );

            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = edit.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");

            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{GetEntityValueName(property)} = {GetEntityTypeFullName(property)}edit.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("CreatedAt = now,");
            stringBuilder.AppendLine("};");
            stringBuilder.AppendLine("}");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine(
            $"queries[i] = edit.{id.Name}.CreateUpdate{type.GetTableName()}Query(updates);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < queries.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("session.ExecuteNonQuery(queries[i]);");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("session.ExecuteNonQuery(events.CreateInsertQuery());");
        stringBuilder.AppendLine("}");
    }

    private void CreateEditMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable} EditEntitiesAsync("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{type.GetNamespace()}.Edit{type.Name}[] edits,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "return EditEntitiesCore(session, userId, transactionId, edits, ct).ConfigureAwait(false);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static async {TypeFullNames.ValueTask} EditEntitiesCore("
        );
        stringBuilder.AppendLine($"global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{type.GetNamespace()}.Edit{type.Name}[] edits,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(edits.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"var ids = edits.Select(x => x.{id.Name}).Distinct().ToArray();");
        stringBuilder.AppendLine("var index = 0;");
        stringBuilder.AppendLine("var eventCount = edits.Sum(x => x.GetEdited());");
        stringBuilder.AppendLine("var now = DateTimeOffset.UtcNow;");
        stringBuilder.AppendLine($"var queries = new {TypeFullNames.SqlQuery}[edits.Length];");

        stringBuilder.AppendLine(
            $"var events = new global::{TypeFullNames.EventEntity}[eventCount];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < edits.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var edit = edits[i];");
        stringBuilder.AppendLine("var updateIndex = 0;");

        stringBuilder.AppendLine(
            $"var updates = new {TypeFullNames.UpdateProperty}[edit.GetEdited()];"
        );

        stringBuilder.AppendLine();

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(edit.IsEdit{property.Name})");
            stringBuilder.AppendLine("{");

            stringBuilder.AppendLine(
                $"updates[updateIndex++] = new global::{TypeFullNames.UpdateProperty}(nameof(edit.{property.Name}), edit.{property.Name});"
            );

            stringBuilder.AppendLine();
            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = edit.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");

            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{GetEntityValueName(property)} = {GetEntityTypeFullName(property)}edit.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("CreatedAt = now,");
            stringBuilder.AppendLine("};");
            stringBuilder.AppendLine("}");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine(
            $"queries[i] = edit.{id.Name}.CreateUpdate{type.GetTableName()}Query(updates);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < queries.Length; i++)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("await session.ExecuteNonQueryAsync(queries[i], ct);");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            "await session.ExecuteNonQueryAsync(events.CreateInsertQuery(), ct);"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateAddMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine("public static void AddEntities(");
        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"params global::{type.GetRealFullName()}[] items)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var index = 0;");

        stringBuilder.AppendLine(
            $"var events = new {TypeFullNames.EventEntity}[items.Length * {properties.Length - 1}];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("foreach (var item in items)");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = item.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{GetEntityValueName(property)} = {GetEntityTypeFullName(property)}item.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("};");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"session.ExecuteNonQuery(events.CreateInsertQuery());");
        stringBuilder.AppendLine("session.ExecuteNonQuery(items.CreateInsertQuery());");
        stringBuilder.AppendLine("}");
    }

    private void CreateAddMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.ConfiguredValueTaskAwaitable} AddEntitiesAsync("
        );
        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{type.GetRealFullName()}[] items,");
        stringBuilder.AppendLine($"{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "return session.AddEntitiesCore(userId, transactionId, items, ct).ConfigureAwait(false);"
        );

        stringBuilder.AppendLine("}");

        stringBuilder.AppendLine(
            $"private static async {TypeFullNames.ValueTask} AddEntitiesCore("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbSession} session,");
        stringBuilder.AppendLine("string userId,");
        stringBuilder.AppendLine("Guid transactionId,");
        stringBuilder.AppendLine($"global::{type.GetRealFullName()}[] items,");
        stringBuilder.AppendLine($"{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var index = 0;");

        stringBuilder.AppendLine(
            $"var events = new {TypeFullNames.EventEntity}[items.Length * {properties.Length - 1}];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("foreach (var item in items)");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"events[index++] = new global::{TypeFullNames.EventEntity}");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine($"EntityId = item.{id.Name},");
            stringBuilder.AppendLine($"EntityType = nameof(global::{type.GetRealFullName()}),");
            stringBuilder.AppendLine(
                $"EntityProperty = nameof({type.GetRealFullName()}.{property.Name}),"
            );

            stringBuilder.AppendLine(
                $"{GetEntityValueName(property)} = {GetEntityTypeFullName(property)}item.{property.Name},"
            );

            stringBuilder.AppendLine("UserId = userId,");
            stringBuilder.AppendLine("TransactionId = transactionId,");
            stringBuilder.AppendLine("};");
            stringBuilder.AppendLine();
        }

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            "await session.ExecuteNonQueryAsync(events.CreateInsertQuery(), ct);"
        );

        stringBuilder.AppendLine(
            "await session.ExecuteNonQueryAsync(items.CreateInsertQuery(), ct);"
        );

        stringBuilder.AppendLine("}");
    }

    private void CreateEditClass(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine($"public class Edit{type.Name}");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"public Edit{type.Name}(global::System.Guid id)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"{id.Name} = id;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public global::System.Guid {id.Name} {{ get; }}");

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"public bool IsEdit{property.Name} {{ get; set; }}");

            stringBuilder.AppendLine(
                $"public global::{property.Type.GetRealFullName()} {property.Name} {{ get; set; }}"
            );
        }

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("public int GetEdited()");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var count = 0;");
        stringBuilder.AppendLine();

        foreach (var property in properties)
        {
            if (id.Name == property.Name)
            {
                continue;
            }

            stringBuilder.AppendLine($"if(IsEdit{property.Name})");
            stringBuilder.AppendLine("{");
            stringBuilder.AppendLine("count++;");
            stringBuilder.AppendLine("}");
        }
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return count;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private string GetEntityValueName(IPropertySymbol property)
    {
        return GetEntityValueName(property.Type);
    }

    private string GetEntityValueName(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { Name: "Nullable" } named)
        {
            return GetEntityValueName(named.TypeArguments[0]);
        }

        if (type is IArrayTypeSymbol array)
        {
            return $"Entity{array.ElementType.GetRealName()}ArrayValue";
        }

        if (type is INamedTypeSymbol { TypeKind: TypeKind.Enum, EnumUnderlyingType: not null } e)
        {
            return $"Entity{e.EnumUnderlyingType.GetRealName()}Value";
        }

        return $"Entity{type.GetRealName()}Value";
    }

    private string GetEntityTypeFullName(IPropertySymbol property)
    {
        if (
            property.Type is INamedTypeSymbol
            {
                TypeKind: TypeKind.Enum,
                EnumUnderlyingType: not null
            } named
        )
        {
            return $"(global::{named.EnumUnderlyingType.GetRealFullName()})";
        }

        return string.Empty;
    }
}
