using Microsoft.CodeAnalysis;

namespace Nestor.SourceGenerator;

[Generator]
public class SqliteAdoGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var assemblyAttributes = context.CompilationProvider.Select(
            (compilation, _) =>
                compilation
                    .Assembly.GetAttributes()
                    .Where(x => x.AttributeClass?.Name == "SqliteAdo")
        );

        context.RegisterSourceOutput(
            assemblyAttributes,
            (spc, attributes) =>
            {
                foreach (var attribute in attributes)
                {
                    if (attribute.ConstructorArguments.Length != 2)
                    {
                        continue;
                    }

                    if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol type)
                    {
                        continue;
                    }

                    if (attribute.ConstructorArguments[1].Value is not string idName)
                    {
                        continue;
                    }

                    var properties = type.GetMembers()
                        .OfType<IPropertySymbol>()
                        .Where(p =>
                            !p.IsStatic && p.SetMethod is not null && p.GetMethod is not null
                        )
                        .ToArray();

                    var id = properties.FirstOrDefault(x => x.Name == idName);

                    if (id is null)
                    {
                        continue;
                    }

                    var stringBuilder = new CSharpStringBuilder(4);
                    stringBuilder.AppendLine("// <auto-generated />");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("#nullable enable");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine("using System.Linq;");
                    stringBuilder.AppendLine("using System.Data;");
                    stringBuilder.AppendLine("using System;");
                    stringBuilder.AppendLine("using System.Threading.Tasks;");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine($"namespace {type.GetNamespace()};");
                    stringBuilder.AppendLine();
                    stringBuilder.AppendLine($"public static class {type.GetTableName()}Ext");
                    stringBuilder.AppendLine("{");
                    AddGetPropertyValueMethod(stringBuilder, type, properties);
                    stringBuilder.AppendLine();
                    AddGetParametersMethods(stringBuilder, type, properties);
                    stringBuilder.AppendLine();
                    AddInsertMethod(stringBuilder, type, properties);
                    stringBuilder.AppendLine();
                    AddUpdateMethod(stringBuilder, type, id);
                    stringBuilder.AppendLine();
                    AddSelectMethod(stringBuilder, type, id);
                    stringBuilder.AppendLine();
                    AddReadMethod(stringBuilder, type, properties);
                    stringBuilder.AppendLine();
                    AddReadMethodA(stringBuilder, type, properties);
                    stringBuilder.AppendLine();
                    AddDeleteMethod(stringBuilder, type, id);
                    stringBuilder.AppendLine();
                    AddToByteArrayMethod(stringBuilder);
                    stringBuilder.AppendLine("}");

                    spc.AddSource($"SqliteAdo.{type}.g.cs", stringBuilder.ToString());
                }
            }
        );
    }

    private void AddGetParametersMethods(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqliteParameter}[] GetSqliteParameters("
        );

        stringBuilder.AppendLine($"this global::{type} value,");
        stringBuilder.AppendLine("string postfix,");

        stringBuilder.AppendLine(
            $"params global::{TypeFullNames.ReadOnlySpan}<string> propertyNames)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(propertyNames.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return [");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine(
                $"new global::{TypeFullNames.SqliteParameter}($\"@{{nameof(value.{property.Name})}}{{postfix}}\", ((object)value.{property.Name}) ?? global::{TypeFullNames.DBNull}.Value),"
            );
        }

        stringBuilder.AppendLine("];");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.SqliteParameter}[propertyNames.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < propertyNames.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new global::{TypeFullNames.SqliteParameter}($\"@{{propertyNames[i]}}{{postfix}}\", value.GetPropertyValue(propertyNames[i]) ?? global::{TypeFullNames.DBNull}.Value);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return parameters;");
        stringBuilder.AppendLine("}");
    }

    private void AddGetPropertyValueMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine("public static object? GetPropertyValue(");
        stringBuilder.AppendLine($"this global::{type} value,");
        stringBuilder.AppendLine("string propertyName)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("switch(propertyName)");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine(
                $"case nameof(value.{property.Name}): return value.{property.Name};"
            );
        }

        stringBuilder.AppendLine(
            $"default: throw new global::{TypeFullNames.ArgumentOutOfRangeException}("
        );

        stringBuilder.AppendLine("nameof(propertyName),");
        stringBuilder.AppendLine("propertyName,");

        stringBuilder.AppendLine(
            "$\"Specified {propertyName} argument {nameof(propertyName)} was out of the range of valid values.\");"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddInsertMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateInsertQuery("
        );

        stringBuilder.AppendLine($"this global::{type}[] values)");

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("return CreateInsertQuery(values.AsSpan());");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine($"public static {TypeFullNames.SqlQuery} CreateInsertQuery(");

        stringBuilder.AppendLine(
            $"this global::{TypeFullNames.ReadOnlySpan}<global::{type}> values)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(values.Length == 0)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine($"throw new {TypeFullNames.ArgumentException}(nameof(values));");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.List}<{TypeFullNames.SqliteParameter}>(values.Length * {properties.Length});"
        );

        stringBuilder.AppendLine("var valueNames = new string[values.Length];");
        stringBuilder.AppendLine($"var sql = \"INSERT INTO {type.GetTableName()} VALUES \";");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < values.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            "parameters.AddRange(values[i].GetSqliteParameters(i.ToString()));"
        );

        stringBuilder.AppendLine(
            $"valueNames[i] = $\"({string.Join(", ", properties.Select(x => $"@{x.Name}{{i}}"))})\";"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("sql += string.Join(\" \", valueNames);");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters.ToArray());");
        stringBuilder.AppendLine("}");
    }

    private void AddUpdateMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateUpdate{type.GetTableName()}Query("
        );

        stringBuilder.AppendLine($"this global::{id.Type.GetRealFullName()} id,");

        stringBuilder.AppendLine(
            $"params {TypeFullNames.ReadOnlySpan}<global::{TypeFullNames.UpdateProperty}> updates)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new global::{TypeFullNames.SqliteParameter}[updates.Length + 1];"
        );

        stringBuilder.AppendLine(
            $"parameters[0] = new global::{TypeFullNames.SqliteParameter}(\"@{id.Name}\", id);"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < updates.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i + 1] = new global::{TypeFullNames.SqliteParameter}($\"@{{updates[i].PropertyName}}\", ((object)updates[i].Value) ?? global::{TypeFullNames.DBNull}.Value);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"var sql = $\"UPDATE {type.GetTableName()} SET {{string.Join(\", \", updates.ToArray().Select(x => $\"{{x.PropertyName}} = @{{x.PropertyName}}\"))}} WHERE {id.Name} = @{id.Name}\";"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return new(sql, parameters);");
        stringBuilder.AppendLine("}");
    }

    private void AddSelectMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public const string SelectQuery = \"SELECT * FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.SqlQuery} CreateSelect{type.GetTableName()}Query(this global::{id.Type.GetRealFullName()}[] ids)"
        );

        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new {TypeFullNames.SqliteParameter}[ids.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < ids.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new {TypeFullNames.SqliteParameter}($\"@Id{{i}}\", ids[i]);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            "return new(SelectQuery + \"WHERE id IN (\" + string.Join(\", \", parameters.Select(x => x.ParameterName)) + \")\", parameters);"
        );

        stringBuilder.AppendLine("}");
    }

    private void AddToByteArrayMethod(CSharpStringBuilder stringBuilder)
    {
        stringBuilder.AppendLine(
            $"private static byte[] ToByteArray(global::{TypeFullNames.Stream} stream)"
        );

        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("var buffer = new byte[stream.Length];");
        stringBuilder.AppendLine("var length = stream.Read(buffer);");
        stringBuilder.AppendLine("stream.Close();");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("return buffer;");
        stringBuilder.AppendLine("}");
    }

    private void AddReadMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.IEnumerable}<global::{type}> Read{type.GetTableName()}("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield break;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("while (reader.Read())");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield return new()");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine($"{property.Name} = {ReadProperty(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddReadMethodA(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol[] properties
    )
    {
        stringBuilder.AppendLine(
            $"public static global::{TypeFullNames.ConfiguredCancelableAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Async("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine(
            $"return Read{type.GetTableName()}Core(reader, ct).ConfigureAwait(false);"
        );
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            $"private static async global::{TypeFullNames.IAsyncEnumerable}<global::{type}> Read{type.GetTableName()}Core("
        );

        stringBuilder.AppendLine($"this global::{TypeFullNames.DbDataReader} reader,");
        stringBuilder.AppendLine($"global::{TypeFullNames.CancellationToken} ct)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("if(!reader.HasRows)");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield break;");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();
        stringBuilder.AppendLine("while (await reader.ReadAsync(ct))");
        stringBuilder.AppendLine("{");
        stringBuilder.AppendLine("yield return new()");
        stringBuilder.AppendLine("{");

        foreach (var property in properties)
        {
            stringBuilder.AppendLine($"{property.Name} = {ReadProperty(property)},");
        }

        stringBuilder.AppendLine("};");
        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine("}");
    }

    private void AddDeleteMethod(
        CSharpStringBuilder stringBuilder,
        INamedTypeSymbol type,
        IPropertySymbol id
    )
    {
        stringBuilder.AppendLine(
            $"public const string DeleteQuery = \"DELETE FROM {type.GetTableName()}\";"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine(
            $"public static {TypeFullNames.SqlQuery} CreateDelete{type.GetTableName()}Query("
        );
        stringBuilder.AppendLine($"this global::{id.Type.GetRealFullName()}[] ids)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"var parameters = new {TypeFullNames.SqliteParameter}[ids.Length];"
        );

        stringBuilder.AppendLine();
        stringBuilder.AppendLine("for(var i = 0; i < ids.Length; i++)");
        stringBuilder.AppendLine("{");

        stringBuilder.AppendLine(
            $"parameters[i] = new {TypeFullNames.SqliteParameter}($\"@Id{{i}}\", ids[i]);"
        );

        stringBuilder.AppendLine("}");
        stringBuilder.AppendLine();

        stringBuilder.AppendLine(
            "return new(DeleteQuery + \"WHERE id IN (\" + string.Join(\", \", parameters.Select(x => x.ParameterName)) + \")\", parameters);"
        );

        stringBuilder.AppendLine("}");
    }

    private string ReadProperty(IPropertySymbol property)
    {
        if (
            property.Type is INamedTypeSymbol
            {
                TypeKind: TypeKind.Enum,
                EnumUnderlyingType: not null,
            } named
        )
        {
            return $"(global::{property.Type}){ReadProperty(named.EnumUnderlyingType.ToString(), property.Name)}";
        }

        return ReadProperty(property.Type.ToString(), property.Name);
    }

    private string ReadProperty(string propertyType, string propertyName)
    {
        return propertyType switch
        {
            "bool" => $"reader.GetBoolean(\"{propertyName}\")",
            "int" => $"reader.GetInt32(\"{propertyName}\")",
            "string" => $"reader.GetString(\"{propertyName}\")",
            "long" => $"reader.GetInt64(\"{propertyName}\")",
            "byte" => $"reader.GetByte(\"{propertyName}\")",
            "ushort" => $"(ushort)reader.GetInt32(\"{propertyName}\")",
            "uint" => $"(uint)reader.GetInt64(\"{propertyName}\")",
            "ulong" => $"reader.GetFieldValue<ulong>(\"{propertyName}\")",
            "sbyte" => $"(sbyte)reader.GetInt16(\"{propertyName}\")",
            "short" => $"reader.GetInt16(\"{propertyName}\")",
            "float" => $"reader.GetFloat(\"{propertyName}\")",
            "double" => $"reader.GetDouble(\"{propertyName}\")",
            "decimal" => $"reader.GetDecimal(\"{propertyName}\")",
            "char" => $"reader.GetChar(\"{propertyName}\")",
            "byte[]" => $"ToByteArray(reader.GetStream(\"{propertyName}\"))",
            TypeFullNames.TimeOnly =>
                $"global::{TypeFullNames.TimeOnly}.Parse(reader.GetString(\"{propertyName}\"))",
            TypeFullNames.TimeSpan =>
                $"global::{TypeFullNames.TimeSpan}.Parse(reader.GetString(\"{propertyName}\"))",
            TypeFullNames.DateOnly =>
                $"global::{TypeFullNames.DateOnly}.Parse(reader.GetString(\"{propertyName}\"))",
            TypeFullNames.DateTime => $"reader.GetDateTime(\"{propertyName}\")",
            TypeFullNames.DateTimeOffset =>
                $"global::{TypeFullNames.DateTimeOffset}.Parse(reader.GetString(\"{propertyName}\"))",
            TypeFullNames.Guid =>
                $"global::{TypeFullNames.Guid}.Parse(reader.GetString(\"{propertyName}\"))",
            _ => propertyType.EndsWith("?")
                ? $"reader.IsDBNull(\"{propertyName}\") ? null : {ReadProperty(propertyType.Substring(0, propertyType.Length - 1), propertyName)}"
                : propertyType,
        };
    }
}
