// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nestor.Db.Sqlite.CompiledModels
{
    public partial class SqliteNestorDbContextModel
    {
        private SqliteNestorDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("62e2e504-f0e2-4454-9db0-3980e83ef556"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var eventEntity = EventEntityEntityType.Create(this);
            var tempEntity = TempEntityEntityType.Create(this);

            EventEntityEntityType.CreateAnnotations(eventEntity);
            TempEntityEntityType.CreateAnnotations(tempEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
