// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace Nestor.Db.Sqlite.CompiledModels
{
    public partial class SqliteNestorDbContextModel
    {
        private SqliteNestorDbContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("672d5560-ef49-4758-b8bd-400488368d1c"), entityTypeCount: 2)
        {
        }

        partial void Initialize()
        {
            var eventEntity = EventEntityEntityType.Create(this);
            var migrationEntity = MigrationEntityEntityType.Create(this);

            EventEntityEntityType.CreateAnnotations(eventEntity);
            MigrationEntityEntityType.CreateAnnotations(migrationEntity);

            AddAnnotation("ProductVersion", "10.0.1");
        }
    }
}
