// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Nestor.Db.Sqlite;
using Nestor.Db.Sqlite.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(SqliteNestorDbContext), typeof(SqliteNestorDbContextModel))]
