// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nestor.Db.Sqlite;

#nullable disable

namespace Nestor.Db.Sqlite.Migrations
{
    [DbContext(typeof(SqliteNestorDbContext))]
    [Migration("20251204162149_AddTempEntity")]
    partial class AddTempEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Nestor.Db.Models.EventEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("EntityBooleanValue")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("EntityByteArrayValue")
                        .HasColumnType("BLOB");

                    b.Property<byte?>("EntityByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<char?>("EntityCharValue")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("EntityDateOnlyValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("EntityDateTimeOffsetValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EntityDateTimeValue")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntityDecimalValue")
                        .HasColumnType("TEXT");

                    b.Property<double?>("EntityDoubleValue")
                        .HasColumnType("REAL");

                    b.Property<Guid?>("EntityGuidValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("TEXT");

                    b.Property<short?>("EntityInt16Value")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EntityInt32Value")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EntityInt64Value")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityProperty")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<sbyte?>("EntitySByteValue")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("EntitySingleValue")
                        .HasColumnType("REAL");

                    b.Property<string>("EntityStringValue")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("EntityTimeOnlyValue")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("EntityTimeSpanValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<ushort?>("EntityUInt16Value")
                        .HasColumnType("INTEGER");

                    b.Property<uint?>("EntityUInt32Value")
                        .HasColumnType("INTEGER");

                    b.Property<ulong?>("EntityUInt64Value")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EventEntity");
                });

            modelBuilder.Entity("Nestor.Db.Models.TempEntity", b =>
                {
                    b.Property<Guid>("EntityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("EntityId");

                    b.ToTable("TempEntity");
                });
#pragma warning restore 612, 618
        }
    }
}
