<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\Nestor.SourceGenerator\Nestor.SourceGenerator.csproj"
      ReferenceOutputAssembly="false"
      OutputItemType="Analyzer"
    />
    <ProjectReference Include="..\..\UltraLiteDB\UltraLiteDB\UltraLiteDB.csproj" />
    <ProjectReference Include="..\Nestor.Db\Nestor.Db.csproj" />
  </ItemGroup>
</Project>
